[project]
name = "hexlet-hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "more-itertools>=10.6.0",
]

[tool.uv.workspace]
members = ["hexlet_hello_world/hexlet-hello-world"]
